commit-msg:
  commands:
    lint-commit-msg:
      run: npx --yes commitlint --edit
pre-commit:
  commands:
    check-format:
      tags: style
      run: ./gradlew spotlessCheck
pre-push:
  parallel: true
  commands:
    licenses-audit:
      tags: licenses audit
      run: ./gradlew checkLicense
    secrets-audit:
      tags: security audit
      run: talisman --githook pre-push
      use_stdin: true
