commit-msg:
  commands:
    lint-commit-msg:
      run: npx --yes commitlint --edit
pre-push:
  parallel: true
  commands:
    secrets-audit:
      tags: security audit
      run: talisman --githook pre-push
      use_stdin: true
